#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <assert.h>
#include <glob.h>

#include "everyline.h"
#include "match.h"
#include "bst.h"
#include "set.h"
#include "analyse.h"


// let's try to write a Makefile..  on stdout for now, but make that
// easy to change via this variable..

static FILE *out;


typedef struct
{
	bool wantspace;
	bool basename;
} pf_data;


// print out the filename (whole or basename, i.e. all but the last
// two characters ".c").  The state pointer is really a pointer to a
// pf_data, we add a leading space if wantspace is true.
// (set wantspace to true for next time).
//
static void printfilename( char *filename, void *state )
{
	pf_data *d = (pf_data *)state;
	if( d->wantspace ) putc( ' ', out );
	d->wantspace = true;
	int len = strlen(filename);
	fprintf( out, "%.*s", d->basename?len-2:len, filename );
}


static void printrule( char *target, void *disguisedset, void *state )
{
	set s = (set)disguisedset;
	int len = strlen(target);
	fprintf( out, "%.*s.o:\t", len-2, target );
	pf_data d = {false, false};
	foreach_set( s, &printfilename, &d );
	fprintf( out, "\n\n" );
}


// char *objects = allobjects( mainsrcfilename, a );
//	Given <mainsrcfilename>, the filename of a C source file
//	containing main(), and an initialized analysis pointer <a>,
//	generate and return a malloc()d string containing
//	a space separated list of all object filenames (.o files)
//	that should be linked together to make the executable
//	of mainsrcfilename.
//	
char *allobjects( char *mainsrcfilename, analysis a )
{
	// TASK 5 (BONUS): IMPLEMENT THIS PROPERLY.

	// THIS IS A STUB: allobjects(X.c) is X.o
	char *s = strdup( mainsrcfilename );
	assert( s != NULL );
	int len = strlen(s);
	s[len-1] = 'o';
	return s;
}


// print out the link target for filename;
// The state pointer is really a pointer to an analysis struct.
//
static void printlink( char *filename, void *state )
{
	analysis ap = state;
	char *objects = allobjects( filename, ap );

	int len = strlen(filename);
	fprintf( out, "%.*s:\t%s\n\n", len-2, filename, objects );
	free( objects );
}


int main( void )
{
	analysis a = analyse();

	out = stdout;			// make it easy to change

	fprintf( out, "# Makefile automatically generated by... us:-)\n\n" );
	fprintf( out, "CFLAGS = -Wall\n" );
	fprintf( out, "CC = gcc\n" );

	// build all main programs, basenames with no initial space:
	fprintf( out, "BUILD = " );
	if( a->mainset != NULL )
	{
		pf_data d;
		d.wantspace = false;
		d.basename = true;
		foreach_set( a->mainset, &printfilename, &d );
	}
	fputc( '\n', out );

	fprintf( out, "\nall:\t$(BUILD)\n\n" );

	fprintf( out, "clean:\t\n\t/bin/rm -f $(BUILD) *.o core .nfs*\n\n" );

	// now print out, for each c2inc, a dependency rule on all includes
	if( a->c2inc != NULL )
	{
		foreach_bst( a->c2inc, &printrule, NULL );
	}

	// finally, print out, for each main program, a link rule
	if( a->mainset != NULL )
	{
		foreach_set( a->mainset, &printlink, &a );
	}

	free_analysis( a );

	return 0;
}
